// (c) Cartesi and individual authors (see AUTHORS)
// SPDX-License-Identifier: Apache-2.0 (see LICENSE)

pragma solidity ^0.8.30;

import {IOwnable} from "../access/IOwnable.sol";
import {AccountValidityProof} from "../common/AccountValidityProof.sol";
import {BinaryMerkleTreeErrors} from "../common/BinaryMerkleTreeErrors.sol";
import {IVersionGetter} from "../common/IVersionGetter.sol";
import {OutputValidityProof} from "../common/OutputValidityProof.sol";
import {WithdrawalConfig} from "../common/WithdrawalConfig.sol";
import {IOutputsMerkleRootValidator} from "../consensus/IOutputsMerkleRootValidator.sol";
import {IRefundOutputBuilder} from "../refund/IRefundOutputBuilder.sol";
import {IRefundOutputBuilderErrors} from "../refund/IRefundOutputBuilderErrors.sol";
import {IWithdrawalOutputBuilder} from "../withdrawal/IWithdrawalOutputBuilder.sol";
import {IWithdrawalOutputBuilderErrors} from "../withdrawal/IWithdrawalOutputBuilderErrors.sol";

/// @notice The base layer incarnation of an application running on the execution layer.
/// @notice The state of the application advances through inputs sent to an `IInputBox` contract.
/// @notice These inputs can be sent either directly, or indirectly through portals.
/// @notice Reader nodes can retrieve inputs sent to the `IInputBox` contract through events, and feed them into the machine.
/// @notice Validator nodes can also submit claims to the `IOutputsMerkleRootValidator` contract (see the `getOutputsMerkleRootValidator` function).
/// @notice Once accepted, claims can be used to validate outputs generated by the machine.
/// @notice Some outputs are executable, which means they can have on-chain side effects.
/// @notice Every application is subscribed to some outputs Merkle root validator, and may be governed by some owner.
/// The outputs Merkle root validator has the power to accept claims, which, in turn, are used to validate outputs.
/// Meanwhile, the owner can replace the outputs Merkle root validator at any time.
/// Therefore, the users of an application must trust both the outputs Merkle root validator and the application owner.
/// @notice There are several ownership models to choose from:
/// - no owner (address zero)
/// - individual signer (externally-owned account)
/// - multiple signers (multi-sig)
/// - DAO (decentralized autonomous organization)
/// - self-owned application (off-chain governance logic)
interface IApplication is
    IOwnable,
    BinaryMerkleTreeErrors,
    IRefundOutputBuilderErrors,
    IWithdrawalOutputBuilderErrors,
    IVersionGetter
{
    // Events

    /// @notice MUST trigger when a new outputs Merkle root validator is chosen.
    /// @param newOutputsMerkleRootValidator The new outputs Merkle root validator
    event OutputsMerkleRootValidatorChanged(IOutputsMerkleRootValidator newOutputsMerkleRootValidator);

    /// @notice MUST trigger when an output is executed.
    /// @param outputIndex The index of the output
    /// @param output The output
    event OutputExecuted(uint64 outputIndex, bytes output);

    /// @notice MUST trigger when the application is foreclosed.
    event Foreclosure();

    /// @notice MUST trigger when a refund for an input is issued.
    /// @param inputIndex The index of the input
    /// @param input The input
    /// @param output The refund output
    event RefundIssued(uint256 inputIndex, bytes input, bytes output);

    /// @notice MUST trigger when the accounts drive Merkle root is proved.
    /// @param accountsDriveMerkleRoot The accounts drive Merkle root
    event AccountsDriveMerkleRootProved(bytes32 accountsDriveMerkleRoot);

    /// @notice MUST trigger when the funds of an account are withdrawn.
    /// @param accountIndex The account index in the accounts drive
    /// @param account The account as encoded in the accounts drive
    /// @param output The withdrawal output
    event Withdrawal(uint64 accountIndex, bytes account, bytes output);

    // Errors

    /// @notice Could not execute an output, because the application contract doesn't know how to.
    /// @param output The output
    error OutputNotExecutable(bytes output);

    /// @notice Could not execute an output, because it was already executed.
    /// @param output The output
    error OutputNotReexecutable(bytes output);

    /// @notice Could not execute an output, because the application contract doesn't have enough Ether.
    /// @param value The amount of Wei necessary for the execution of the output
    /// @param balance The current application contract balance
    error InsufficientFunds(uint256 value, uint256 balance);

    /// @notice Raised when the output hashes siblings array has an invalid size.
    /// @dev Please consult `CanonicalMachine` for the maximum number of outputs.
    error InvalidOutputHashesSiblingsArrayLength();

    /// @notice Raised when the computed outputs Merkle root is invalid, according to the current outputs Merkle root validator.
    error InvalidOutputsMerkleRoot(bytes32 outputsMerkleRoot);

    /// @notice Raised when a function that can only be called by
    /// the application guardian is called by some other account.
    error NotGuardian();

    /// @notice Raised when the application has not yet been foreclosed
    /// and therefore withdrawal-related actions cannot be performed yet.
    error NotForeclosed();

    /// @notice Raised when the application has been foreclosed
    /// and therefore some actions cannot be performed anymore.
    error Foreclosed();

    /// @notice Raised when trying to decode the data availability byte array,
    /// but either it is ill-formed or encodes an unknown data availability solution.
    error UnknownDataAvailability();

    /// @notice Raised when trying to validate an input with an invalid index.
    /// @param invalidInputIndex The invalid input index provided for validation
    /// @param numOfInputs The actual number of inputs to the application
    /// @dev This error is raised when invalidInputIndex >= numOfInputs.
    error InvalidInputIndex(uint256 invalidInputIndex, uint256 numOfInputs);

    /// @notice Raised when trying to validate an input with an invalid hash.
    /// @param storedInputHash The hash of the input stored in the input box
    /// @param invalidInputHash The invalid input hash provided for validation
    /// @dev This error is raised when storedInputHash != invalidInputHash.
    error InvalidInputHash(bytes32 storedInputHash, bytes32 invalidInputHash);

    /// @notice Raised when decoding an ill-formed input.
    /// @dev This error should never be raised if the application uses
    /// the canonical input box contract as on-chain data availability.
    error IllFormedInput();

    /// @notice Raised when trying to issue a refund for a finalized input.
    /// @param inputIndex The input index
    error CannotRefundFinalizedInput(uint256 inputIndex);

    /// @notice Raised when trying to re-issue a refund for the same input.
    /// @param inputIndex The input index
    error RefundAlreadyIssued(uint256 inputIndex);

    /// @notice Raised when the accounts drive Merkle root proof size is invalid.
    /// @dev The array length should be log2 of the machine memory size - log2 of the
    /// accounts drive size. See the `CanonicalMachine` library and the
    /// `getLog2MaxNumOfAccounts` and `getLog2LeavesPerAccount` functions.
    error InvalidAccountsDriveMerkleRootProofSize();

    /// @notice Raised when someone tries to prove the accounts drive Merkle root but it
    /// has already been proved. This error adds an extra layer of protection against
    /// consensus-takeover attacks in which `getLastFinalizedMachineMerkleRoot` returns
    /// a different value after the application is foreclosed.
    error AccountsDriveMerkleRootAlreadyProved();

    /// @notice Raised when someone tries to validate an accounts Merkle root but the
    /// accounts drive Merkle root has not yet been proved through the
    /// `proveAccountsDriveMerkleRoot` function.
    error AccountsDriveMerkleRootNotProved();

    /// @notice Raised when the account root siblings array has an invalid length.
    /// @dev The array length should be log2 of the maximum number of accounts. See the
    /// `getLog2MaxNumOfAccounts` function.
    error InvalidAccountRootSiblingsArrayLength();

    /// @notice Raised when the computed machine Merkle root differs from the
    /// last-finalized machine Merkle root provided by the outputs Merkle root validator
    /// or from the initial machine Merkle root (template hash) if no machine Merkle root
    /// has been finalized yet.
    /// @param machineMerkleRoot The computed machine Merkle root
    error InvalidMachineMerkleRoot(bytes32 machineMerkleRoot);

    /// @notice Raised when the computed accounts drive Merkle root differs
    /// from the one proved through the `proveAccountsDriveMerkleRoot` function.
    /// @param accountsDriveMerkleRoot The computed accounts drive Merkle root
    error InvalidAccountsDriveMerkleRoot(bytes32 accountsDriveMerkleRoot);

    /// @notice Raised when trying to withdraw funds of an account
    /// whose funds have already been withdrawn.
    /// @param accountIndex The account index
    error AccountFundsAlreadyWithdrawn(uint64 accountIndex);

    // Permissioned functions

    /// @notice Migrate the application to a new outputs Merkle root validator.
    /// @param newOutputsMerkleRootValidator The new outputs Merkle root validator
    /// @dev Can only be called by the application owner.
    /// May raise `OwnableUnauthorizedAccount` or `Foreclosed`.
    function migrateToOutputsMerkleRootValidator(IOutputsMerkleRootValidator newOutputsMerkleRootValidator)
        external;

    /// @notice Forecloses the application, allowing users to withdraw their funds
    /// by providing Merkle proofs of their in-app accounts.
    /// @dev Can only be called by the application guardian.
    /// May raise `NotGuardian` or `Foreclosed`.
    function foreclose() external;

    // Permissionless functions

    /// @notice Execute an output.
    /// @param output The output
    /// @param proof The proof used to validate the output against
    ///              a claim accepted to the current outputs Merkle root validator contract
    /// @dev On a successful execution, emits a `OutputExecuted` event.
    /// @dev May raise any of the errors raised by `validateOutput`,
    /// as well as `OutputNotExecutable` and `OutputNotReexecutable`.
    function executeOutput(bytes calldata output, OutputValidityProof calldata proof)
        external;

    /// @notice Issue a refund for an unprocessed input.
    /// @param inputIndex The index of the input in the application's input box.
    /// @param input The input that was sent to the application
    /// @dev May raise `CannotRefundFinalizedInput`, `RefundAlreadyIssued`,
    /// `UnknownInputSender`, as well as any of the errors raised by `validateInput`.
    /// On success, marks the input as refunded, and emits a `RefundIssued` event.
    function issueRefund(uint256 inputIndex, bytes calldata input) external;

    /// @notice Prove the accounts drive Merkle root in the last-finalized machine state
    /// provided by the application's outputs Merkle root validator or in the initial
    /// machine Merkle root (template hash) if no machine Merkle root has been finalized
    /// yet. This function can be called by anyone after the app is foreclosed so that
    /// accounts can be validated and their funds can be withdrawn.
    /// @param accountsDriveMerkleRoot The accounts drive Merkle root
    /// @param proof Siblings of the accounts drive Merkle root in the machine
    /// @dev May raise `NotForeclosed`, `AccountsDriveMerkleRootAlreadyProved`,
    /// `InvalidAccountsDriveMerkleRootProofSize` or `InvalidMachineMerkleRoot`.
    /// On success, stores the proved accounts drive Merkle root and emits an
    /// `AccountsDriveMerkleRootProved` event.
    function proveAccountsDriveMerkleRoot(
        bytes32 accountsDriveMerkleRoot,
        bytes32[] calldata proof
    ) external;

    /// @notice Withdraw the funds of an account from the foreclosed application.
    /// First, the account is validated against the proved accounts drive Merkle root.
    /// Then, a withdrawal output is built from the account, and executed.
    /// @param account The account
    /// @param proof The proof used to validate the account
    /// @dev May raise `NotForeclosed`, `AccountFundsAlreadyWithdrawn`,
    /// as well as any of the errors raised by `validateAccount`.
    /// On success, marks the account funds as withdrawn, and emits a `Withdrawal` event.
    function withdraw(bytes calldata account, AccountValidityProof calldata proof)
        external;

    /// @notice Check whether an output has been executed.
    /// @param outputIndex The index of output
    /// @return Whether the output has been executed before
    function wasOutputExecuted(uint256 outputIndex) external view returns (bool);

    /// @notice Validate an output.
    /// @param output The output
    /// @param proof The proof used to validate the output against
    ///              a claim accepted to the current outputs Merkle root validator contract
    /// @dev May raise any of the errors raised by `validateOutputHash`.
    function validateOutput(bytes calldata output, OutputValidityProof calldata proof)
        external
        view;

    /// @notice Validate an output hash.
    /// @param outputHash The output hash
    /// @param proof The proof used to validate the output against
    ///              a claim accepted to the current outputs Merkle root validator contract
    /// @dev May raise `InvalidOutputHashesSiblingsArrayLength`
    /// or `InvalidOutputsMerkleRoot`.
    function validateOutputHash(bytes32 outputHash, OutputValidityProof calldata proof)
        external
        view;

    /// @notice Get the application's template hash.
    /// @return The application's template hash
    function getTemplateHash() external view returns (bytes32);

    /// @notice Get the current outputs Merkle root validator.
    /// @return The current outputs Merkle root validator
    function getOutputsMerkleRootValidator()
        external
        view
        returns (IOutputsMerkleRootValidator);

    /// @notice Get the data availability solution used by application.
    /// @return Solidity ABI-encoded function call that describes
    /// the source of inputs that should be fed to the application.
    function getDataAvailability() external view returns (bytes memory);

    /// @notice Get number of block in which contract was deployed
    function getDeploymentBlockNumber() external view returns (uint256);

    /// @notice Get number of outputs executed by the application.
    function getNumberOfExecutedOutputs() external view returns (uint256);

    /// @notice Check whether the application has been foreclosed.
    /// An application that has been foreclosed will remain so.
    function isForeclosed() external view returns (bool);

    /// @notice Get the address of the guardian,
    /// which has the power to foreclose the application.
    function getGuardian() external view returns (address);

    /// @notice Get the withdrawal configuration set upon construction.
    /// @return withdrawalConfig The withdrawal configuration
    function getWithdrawalConfig()
        external
        view
        returns (WithdrawalConfig memory withdrawalConfig);

    /// @notice Get the number of issued refunds.
    /// Useful for fast-syncing `RefundIssued` events.
    function getNumberOfIssuedRefunds() external view returns (uint256);

    /// @notice Check whether a refund had been issued for an input.
    /// @param inputIndex The index of the input in the application's input box
    function wasRefundForInputIssued(uint256 inputIndex) external view returns (bool);

    /// @notice Check whether the accounts drive Merkle root was proved and its value.
    /// @return wasAccountsDriveMerkleRootProved Whether the accounts drive Merkle root was proved
    /// @return accountsDriveMerkleRoot The accounts drive Merkle root (if proved)
    function getAccountsDriveMerkleRoot()
        external
        view
        returns (bool wasAccountsDriveMerkleRootProved, bytes32 accountsDriveMerkleRoot);

    /// @notice Get the number of withdrawals.
    /// Useful for fast-syncing `Withdrawal` events.
    function getNumberOfWithdrawals() external view returns (uint256);

    /// @notice Check whether an account had its funds withdrawn.
    /// @param accountIndex The index of the account in the accounts drive.
    function wereAccountFundsWithdrawn(uint256 accountIndex) external view returns (bool);

    /// @notice Get the log (base 2) of the number of leaves
    /// in the machine state tree that are reserved for
    /// each account in the accounts drive.
    function getLog2LeavesPerAccount() external view returns (uint8);

    /// @notice Get the log (base 2) of the maximum number
    /// of accounts that can be stored in the accounts drive.
    /// @notice This is equivalent to the depth of the accounts
    /// drive tree whose leaves are the account roots.
    function getLog2MaxNumOfAccounts() external view returns (uint8);

    /// @notice Get the factor that, when multiplied by the size of the accounts
    /// drive, yields the start memory address of the accounts drive.
    /// @dev If `a = getLog2LeavesPerAccount()` `b = getLog2MaxNumOfAccounts()`,
    /// and `c = getAccountsDriveStartIndex()`, then the accounts drive starts
    /// at memory address `c*2^{a+b+5}` and has `2^{a+b+5}` bytes in size.
    function getAccountsDriveStartIndex() external view returns (uint64);

    /// @notice Get the refund output builder, which gets static-called
    /// whenever a deposit is to be refunded to the original depositor.
    function getRefundOutputBuilder() external view returns (IRefundOutputBuilder);

    /// @notice Validates an input that was sent to the application.
    /// @param inputIndex The index of the input in the application's input box.
    /// @param input The input that was sent to the application
    /// @return blockNumber The number of the base-layer block in which the input was added
    /// @return inputSender The input sender
    /// @return inputPayload The input payload
    /// @dev May raise `IllFormedInput` as well as any of the errors raised by `validateInputHash`.
    function validateInput(uint256 inputIndex, bytes calldata input)
        external
        view
        returns (uint256 blockNumber, address inputSender, bytes memory inputPayload);

    /// @notice Validates an input that was sent to the application.
    /// @param inputIndex The index of the input in the application's input box.
    /// @param inputHash The hash of the input that was sent to the application
    /// @dev May raise `UnknownDataAvailability`, `InvalidInputIndex` or `InvalidInputHash`.
    function validateInputHash(uint256 inputIndex, bytes32 inputHash) external view;

    /// @notice Get the withdrawal output builder, which gets static-called
    /// whenever the funds of an account are to be withdrawn.
    function getWithdrawalOutputBuilder() external view returns (IWithdrawalOutputBuilder);

    /// @notice Validate the existence of an account at a given index
    /// on the accounts drive given a Merkle proof of the account root,
    /// according to the accounts drive Merkle root proved through the
    /// `proveAccountsDriveMerkleRoot` function.
    /// @param account The account
    /// @param proof The proof used to validate the account
    /// @dev May raise any of the errors raised by `validateAccountMerkleRoot`,
    /// as well as `DriveSmallerThanData` (if the provided account is too large).
    function validateAccount(bytes calldata account, AccountValidityProof calldata proof)
        external
        view;

    /// @notice Validate the existence of an account at a given index
    /// on the accounts drive given a Merkle proof of the account root,
    /// according to the accounts drive Merkle root proved through the
    /// `proveAccountsDriveMerkleRoot` function.
    /// @param accountMerkleRoot The account Merkle root
    /// @param proof The proof used to validate the account
    /// @dev May raise `InvalidAccountRootSiblingsArrayLength`, `InvalidNodeIndex`
    /// (if the account index is outside the boundaries of the accounts drive),
    /// `AccountsDriveMerkleRootNotProved` or `InvalidAccountsDriveMerkleRoot`.
    function validateAccountMerkleRoot(
        bytes32 accountMerkleRoot,
        AccountValidityProof calldata proof
    ) external view;
}
