name: "Install dependencies"
description: "Installs Foundry and Solidity packages"

runs:
  using: "composite"
  steps:
    - name: Set Foundry version
      id: set-foundry-version
      shell: bash
      run: echo "foundry-version=$(make print-foundry-version)" >> $GITHUB_OUTPUT

    - uses: foundry-rs/foundry-toolchain@c7450ba673e133f5ee30098b3b54f444d3a2ca2d # v1.8.0
      with:
        version: ${{ steps.set-foundry-version.outputs.foundry-version }}

    - name: Install Solidity packages
      shell: bash
      run: forge soldeer install
