name: 'Install dependencies'
description: 'Installs pnpm, node, Node packages, foundry, and soldeer packages'

outputs:
  foundry-version:
    description: 'The version of Foundry that was installed'
    value: ${{ steps.set-foundry-version.outputs.foundry-version }}

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0

    - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version: 22
        cache: 'pnpm'

    - name: Install Node packages
      shell: bash
      run: pnpm install

    - name: Set Foundry version
      id: set-foundry-version
      shell: bash
      run: echo "foundry-version=v1.4.2" >> $GITHUB_OUTPUT

    - uses: foundry-rs/foundry-toolchain@de808b1eea699e761c404bda44ba8f21aba30b2c # 1.3.1
      with:
        version: ${{ steps.set-foundry-version.outputs.foundry-version }}

    - name: Install Solidity packages
      shell: bash
      run: forge soldeer install
