name: "Install dependencies"
description: "Installs Foundry and Solidity packages"

runs:
  using: "composite"
  steps:
    - name: Set Foundry version
      id: set-foundry-version
      shell: bash
      run: echo "foundry-version=$(make print-foundry-version)" >> $GITHUB_OUTPUT

    - uses: foundry-rs/foundry-toolchain@908c540300062bd5a7e473851cdb4282204cee09 # v1.9.1
      with:
        version: ${{ steps.set-foundry-version.outputs.foundry-version }}

    - name: Install Solidity packages
      shell: bash
      run: make install-deps
