name: 'Install dependencies'
description: 'Installs pnpm, node, Node packages, foundry, and soldeer packages'

outputs:
  foundry-version:
    description: 'The version of Foundry that was installed'
    value: ${{ steps.set-foundry-version.outputs.foundry-version }}

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v3

    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'

    - name: Install Node packages
      shell: bash
      run: pnpm install

    - name: Set Foundry version
      id: set-foundry-version
      shell: bash
      run: echo "foundry-version=v1.0.0" >> $GITHUB_OUTPUT

    - uses: foundry-rs/foundry-toolchain@v1
      with:
        version: ${{ steps.set-foundry-version.outputs.foundry-version }}

    - name: Install Solidity packages
      shell: bash
      run: forge soldeer install
