name = "cartesi-rollups-add-input"
version = "0.0.1"

[pull.cartesiRollups]
source = "cartesi-rollups:2.0.0-rc.18@main"

[invoke.addFirstInput]
target = "cartesiRollups.InputBox"
func = "addInput"
args = [
    "<%= cartesiRollups.InputBox.address %>",
    "0x"
]

[invoke.addInput0]
target = "cartesiRollups.InputBox"
func = "addInput"
args = [
    "<%= cartesiRollups.InputBox.address %>",
    "0x<%= ('ff').repeat(2**0) %>"
]
depends = ["invoke.addFirstInput"]

[invoke.addInput1]
target = "cartesiRollups.InputBox"
func = "addInput"
args = [
    "<%= cartesiRollups.InputBox.address %>",
    "0x<%= ('ff').repeat(2**1) %>"
]
depends = ["invoke.addFirstInput"]

[invoke.addInput2]
target = "cartesiRollups.InputBox"
func = "addInput"
args = [
    "<%= cartesiRollups.InputBox.address %>",
    "0x<%= ('ff').repeat(2**2) %>"
]
depends = ["invoke.addFirstInput"]

[invoke.addInput3]
target = "cartesiRollups.InputBox"
func = "addInput"
args = [
    "<%= cartesiRollups.InputBox.address %>",
    "0x<%= ('ff').repeat(2**3) %>"
]
depends = ["invoke.addFirstInput"]

[invoke.addInput4]
target = "cartesiRollups.InputBox"
func = "addInput"
args = [
    "<%= cartesiRollups.InputBox.address %>",
    "0x<%= ('ff').repeat(2**4) %>"
]
depends = ["invoke.addFirstInput"]

[invoke.addInput5]
target = "cartesiRollups.InputBox"
func = "addInput"
args = [
    "<%= cartesiRollups.InputBox.address %>",
    "0x<%= ('ff').repeat(2**5) %>"
]
depends = ["invoke.addFirstInput"]

[invoke.addInput6]
target = "cartesiRollups.InputBox"
func = "addInput"
args = [
    "<%= cartesiRollups.InputBox.address %>",
    "0x<%= ('ff').repeat(2**6) %>"
]
depends = ["invoke.addFirstInput"]

[invoke.addInput7]
target = "cartesiRollups.InputBox"
func = "addInput"
args = [
    "<%= cartesiRollups.InputBox.address %>",
    "0x<%= ('ff').repeat(2**7) %>"
]
depends = ["invoke.addFirstInput"]

[invoke.addInput8]
target = "cartesiRollups.InputBox"
func = "addInput"
args = [
    "<%= cartesiRollups.InputBox.address %>",
    "0x<%= ('ff').repeat(2**8) %>"
]
depends = ["invoke.addFirstInput"]

[invoke.addInput9]
target = "cartesiRollups.InputBox"
func = "addInput"
args = [
    "<%= cartesiRollups.InputBox.address %>",
    "0x<%= ('ff').repeat(2**9) %>"
]
depends = ["invoke.addFirstInput"]

[invoke.addInput10]
target = "cartesiRollups.InputBox"
func = "addInput"
args = [
    "<%= cartesiRollups.InputBox.address %>",
    "0x<%= ('ff').repeat(2**10) %>"
]
depends = ["invoke.addFirstInput"]

[invoke.addInput11]
target = "cartesiRollups.InputBox"
func = "addInput"
args = [
    "<%= cartesiRollups.InputBox.address %>",
    "0x<%= ('ff').repeat(2**11) %>"
]
depends = ["invoke.addFirstInput"]

[invoke.addInput12]
target = "cartesiRollups.InputBox"
func = "addInput"
args = [
    "<%= cartesiRollups.InputBox.address %>",
    "0x<%= ('ff').repeat(2**12) %>"
]
depends = ["invoke.addFirstInput"]

[invoke.addInput13]
target = "cartesiRollups.InputBox"
func = "addInput"
args = [
    "<%= cartesiRollups.InputBox.address %>",
    "0x<%= ('ff').repeat(2**13) %>"
]
depends = ["invoke.addFirstInput"]

[invoke.addInput14]
target = "cartesiRollups.InputBox"
func = "addInput"
args = [
    "<%= cartesiRollups.InputBox.address %>",
    "0x<%= ('ff').repeat(2**14) %>"
]
depends = ["invoke.addFirstInput"]

[invoke.addInput15]
target = "cartesiRollups.InputBox"
func = "addInput"
args = [
    "<%= cartesiRollups.InputBox.address %>",
    "0x<%= ('ff').repeat(2**15) %>"
]
depends = ["invoke.addFirstInput"]

[invoke.addInput16]
target = "cartesiRollups.InputBox"
func = "addInput"
args = [
    "<%= cartesiRollups.InputBox.address %>",
    "0x<%= ('ff').repeat(2**16) %>"
]
depends = ["invoke.addFirstInput"]

[invoke.addInput17]
target = "cartesiRollups.InputBox"
func = "addInput"
args = [
    "<%= cartesiRollups.InputBox.address %>",
    "0x<%= ('ff').repeat(2**17) %>"
]
depends = ["invoke.addFirstInput"]
