[profile.default]
libs = ["dependencies"]
auto_detect_remappings = false
solc_version = "0.8.30"
via_ir = true
optimizer = true
evm_version = "prague"
always_use_create_2_factory = true
remappings = [
    "@openzeppelin-contracts-5.2.0/=dependencies/@openzeppelin-contracts-5.2.0/",
    "cartesi-machine-solidity-step-0.15.0/=dependencies/cartesi-machine-solidity-step-0.15.0/",
    "forge-std-1.9.6/=dependencies/forge-std-1.9.6/",
]
fs_permissions = [
    { access = "read-write", path = "deployments" },
    { access = "read-write", path = "script/utils/ContractDeployers.sol" },
    { access = "read-write", path = "src/common/Version.sol" },
]

[fmt]
line_length = 90
sort_imports = true
single_line_imports = true
docs_style = "line"

[doc]
out = "forge-docs"

[invariant]
runs = 32
depth = 100
fail_on_revert = true

[soldeer]
remappings_location = "config"

[lint]
exclude_lints = ["incorrect-shift", "unsafe-cheatcode"]

[dependencies]
"@openzeppelin-contracts" = "5.2.0"
forge-std = "1.9.6"
cartesi-machine-solidity-step = { version = "0.15.0", git = "https://github.com/cartesi/machine-solidity-step.git", tag = "v0.15.0" }

[rpc_endpoints]
arb_mainnet = "${ARB_MAINNET_RPC_URL}"
arb_sepolia = "${ARB_SEPOLIA_RPC_URL}"
base_mainnet = "${BASE_MAINNET_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
eth_mainnet = "${ETH_MAINNET_RPC_URL}"
eth_sepolia = "${ETH_SEPOLIA_RPC_URL}"
opt_mainnet = "${OPT_MAINNET_RPC_URL}"
opt_sepolia = "${OPT_SEPOLIA_RPC_URL}"

# See more config options https://book.getfoundry.sh/reference/config/
