name: Install dependencies

on:
  workflow_call:
    inputs:
      foundry-version:
        description: 'Foundry version'
        required: true
        type: string

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v3
      with:
        version: 8

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Install Node packages
      shell: bash
      run: pnpm i

    - uses: foundry-rs/foundry-toolchain@v1
      with:
        version: ${{ inputs.foundry-version }}
