// (c) Cartesi and individual authors (see AUTHORS)
// SPDX-License-Identifier: Apache-2.0 (see LICENSE)

pragma solidity ^0.8.8;

/// @title Outputs
/// @notice Defines the signatures of outputs that can be generated by the
/// off-chain machine and verified by the on-chain contracts.
interface Outputs {
    /// @notice A piece of verifiable information.
    /// @param notice An arbitrary blob.
    function Notice(bytes calldata notice) external;

    /// @notice A single-use permission to execute a specific message call
    /// from the context of the application contract.
    /// @param destination The address that will be called
    /// @param payload The payload, which—in the case of Solidity
    /// contracts—encodes a function call
    function Voucher(address destination, bytes calldata payload) external;
}
