# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build
on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-d369d2486f85576eec4ca41d277391dfdae21ba7

      - name: Install dependencies
        run: yarn
        working-directory: onchain/rollups

      - name: Generate proofs
        run: yarn proofs:setup
        working-directory: onchain/rollups

      - name: Run tests
        run: yarn test
        working-directory: onchain/rollups
