name: Publish package to npmjs
on:
  push:
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: onchain/rollups

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn install

      - name: Publish package
        if: ${{ ! contains(github.ref_name, '-rc.') }}
        run: yarn npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish release candidate
        if: ${{ contains(github.ref_name, '-rc.') }}
        run: yarn npm publish --access public --tag rc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
