name: Remove docker images for stale/closed PR(s).
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  cleanup:
    name: Cleanup ghcr.io/cartesi/${{ matrix.image }}:pr-${{ github.event.number }} image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        image:
          - rollups-cli
          - rollups-deployments
          - rollups-hardhat
    steps:
      - uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          organization: cartesi
          container: ${{ matrix.image }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prune-untagged: false
          keep-last: 0
          prune-tags-regexes: |
            ^pr-${{ github.event.number }}$
