name: Upload contracts

on:
  pull_request:
  push:
    branches:
      - main
      - release/*
      - next/*
    tags:
      - v*

jobs:
  push:
    name: Publish contracts to Soldeer.xyz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup
        id: setup

      - name: Extract version from tag
        id: extract_version
        run: |
          if [[ "$GITHUB_REF" == refs/tags/v* ]]; then
            echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            echo "version=0.0.0-dev" >> $GITHUB_OUTPUT
          fi

      - name: Push package to Soldeer.xyz
        run: |
          if [ "$DRY_RUN" = "true" ]; then
            forge soldeer push "cartesi-rollups-contracts~$VERSION" --dry-run
          else
            forge soldeer push "cartesi-rollups-contracts~$VERSION"
          fi
        env:
          DRY_RUN: ${{ !startsWith(github.ref, 'refs/tags/v') }}
          SOLDEER_API_TOKEN: ${{ startsWith(github.ref, 'refs/tags/v') && secrets.SOLDEER_API_TOKEN || '' }}
          VERSION: ${{ steps.extract_version.outputs.version }}